### ISSUE TITLE
Missing instructions for the embeddded login implementation

### ISSUE THREAD

**Issue by rafanog** [auth0-community/auth0-cycle-samples#9]
There are no instructions on how to create an embedded version of the login, neither a branch on the repo for this option.

**Comment by beardaway** [comment]
Hey there @rafanog !

Sorry for such huge delay in response! We'll currently discussing strategies on maintaining those repos as beforehand we simply didn't have enough internal bandwidth to do that and we outsourced it to community developers. I'll make sure to relay your feedback to appropriate people and advocate for your needs! In the meantime, I'm closing this one to be re-opened once we organise some internal bandwidth to look on that repo! Thank you and sorry for any inconvenience!
